### ISSUE TITLE
Assignment 8 Completed 

### ISSUE THREAD

**Issue by emilykschwabe** [emilykschwabe/Assignment-8#1]
Hi Mark, 

Just finished the isopresentation. I modified the YAML, added break slides, bulleted slides and I added an image. A nice final assignment! Thanks.

**Comment by mdscheuerell** [comment]
Well done, Emily! I just wanted to say that you were the only undergrad in class, but no one would have ever known. Your work/attendance was excellent. I'd be happy to write you a letter of recommendation in the future, if you ever need one.

**Comment by emilykschwabe** [comment]
Hi Mark,

Thank you for taking the time to send me this message. I appreciate what
you said. I may be taking you up on that offer very soon as I am currently
on the job hunt! I'll keep in touch. Have a great break! Thank you.

Best,
Emily
